version: '2'
services:
  app:
    build: .
    env_file: backend/.env-docker.list
    tty: true
    command: "npm run test"
    links:
      - mongo
      - postgres
  mongo:
    image: mongo:3.6.2
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
